name: Build JsonPatch library

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    name: Build JsonPatch library
    runs-on: windows-latest
    steps:

    - name: '📄 Checkout'
      uses: actions/checkout@v3

    - name: 🛠️ Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: 🛠️ Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
        nuget-version: '5.x'

    - name: 🛠️ Restore NuGet packages
      run: nuget restore JsonPatch.sln